name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Substitua se você usa outra branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli  # Instala o Angular CLI globalmente

      - name: Build Angular app
        run: ng build --output-path docs --base-href /trampa-aqui/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Esta deve ser a branch de deploy
          folder: docs      # Pasta onde o build do Angular foi salvo
